quarkus:
  application:
    name: quarkus-demo

  http:
    port: 9527

  datasource:
    db-kind: h2
    username: quarkus
    password: quarkus
    jdbc:
      validation-query-sql: select 1
      url: jdbc:h2:~/quarkus_test_db

  hibernate-orm:
    log:
      sql: true
